# Site settings
title: ArtCoin
email: info@joinartcoin.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: joinartcoin
github_username: art-coin
instagram_username: joinartcoin

# Build settings
markdown: kramdown
